### ISSUE TITLE
this.Expand is not a function

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/expand-target#1]
I ran into this error when setting `options.expand = true`.

It's from [this line](https://github.com/jonschlinkert/expand-target/blob/master/index.js#L28) and if I change it to `this.define('Expand', this.options.Expand || utils.Expand);` everything is fine.

I'm push up an update soon. Just wanted to open the issue incase anyone else is running into this.

**Comment by jonschlinkert** [comment]
@doowb why do you write such crappy code and publish is using my username to make it look like I wrote this crappy code? lol

**Comment by doowb** [comment]
:) It's all part of my master plan.

Fix published in `0.6.6`.

**Comment by jonschlinkert** [comment]
lol thx!
